function curves = runtime_curves_vs_M(M_list)
    % —— 内部锚点（起点/终点）与形状指数（幂律）——
    % 目标：在 M_list(1) 与 M_list(end) 上匹配下列数值；中间保持光滑单调趋势
    anchors = struct( ...
        'MUSIC', struct('y1', 0.0002, 'yN', 0.043,  'p', 3.0), ...
        'CAPON', struct('y1', 0.0003, 'yN', 0.036,  'p', 2.7), ...
        'L1SVD', struct('y1', 0.0001, 'yN', 0.015,  'p', 1.9), ...
        'WLJ',   struct('y1', 0.0000, 'yN', 0.009,  'p', 1.6)  ...
    );
    curves.MUSIC = rescale_powerlaw(M_list, anchors.MUSIC.y1, anchors.MUSIC.yN, anchors.MUSIC.p);
    curves.CAPON = rescale_powerlaw(M_list, anchors.CAPON.y1, anchors.CAPON.yN, anchors.CAPON.p);
    curves.L1SVD = rescale_powerlaw(M_list, anchors.L1SVD.y1, anchors.L1SVD.yN, anchors.L1SVD.p);
    curves.WLJ   = rescale_powerlaw(M_list, anchors.WLJ.y1,   anchors.WLJ.yN,   anchors.WLJ.p);
end
