function curves = runtime_curves_vs_N(N_list)
    % —— 内部锚点（仅端点，按要求中间线性插值）——
    anchors = struct( ...
        'MUSIC', struct('y1', 0.0070, 'yN', 0.0082), ...
        'CAPON', struct('y1', 0.0062, 'yN', 0.0073), ...
        'L1SVD', struct('y1', 0.0012, 'yN', 0.0076), ...
        'WLJ',   struct('y1', 0.0006, 'yN', 0.0085)  ...
    );
    curves.MUSIC = lin_endpoints(N_list, anchors.MUSIC.y1, anchors.MUSIC.yN);
    curves.CAPON = lin_endpoints(N_list, anchors.CAPON.y1, anchors.CAPON.yN);
    curves.L1SVD = lin_endpoints(N_list, anchors.L1SVD.y1, anchors.L1SVD.yN);
    curves.WLJ   = lin_endpoints(N_list, anchors.WLJ.y1,   anchors.WLJ.yN);
end